export enum AuthQueues {
    AUTH_MAIL = 'AUTH_MAIL_QUEUE',
    AUTH_USER = 'AUTH_USER_QUEUE',
}

export enum AuthMailJobs {
    SEND_REGISTER_CODE = 'AUTH_SEND_REGISTER_CODE',
    SEND_RESET_PASSWORD = 'AUTH_SEND_RESET_PASSWORD',
    SEND_CHANGE_EMAIL = 'AUTH_SEND_CHANGE_EMAIL',
}

export enum AuthUserJobs {
    CREATE_WORKSPACE = 'AUTH_CREATE_WORKSPACE',
}
